
var VORONOI_WASM = (new function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(VORONOI_WASM) {
  VORONOI_WASM = VORONOI_WASM || {};


var b;b||(b=typeof VORONOI_WASM !== 'undefined' ? VORONOI_WASM : {});var e={},h;for(h in b)b.hasOwnProperty(h)&&(e[h]=b[h]);var k=!1,m=!1,n=!1,p=!1;k="object"===typeof window;m="function"===typeof importScripts;n="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;p=!k&&!n&&!m;var q="",r,t,u,v;
if(n)q=m?require("path").dirname(q)+"/":__dirname+"/",r=function(a,c){u||(u=require("fs"));v||(v=require("path"));a=v.normalize(a);return u.readFileSync(a,c?null:"utf8")},t=function(a){a=r(a,!0);a.buffer||(a=new Uint8Array(a));a.buffer||w("Assertion failed: undefined");return a},1<process.argv.length&&process.argv[1].replace(/\\/g,"/"),process.argv.slice(2),process.on("uncaughtException",function(a){throw a;}),process.on("unhandledRejection",w),b.inspect=function(){return"[Emscripten Module object]"};
else if(p)"undefined"!=typeof read&&(r=function(a){return read(a)}),t=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");"object"===typeof a||w("Assertion failed: undefined");return a},"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(k||m)m?q=self.location.href:document.currentScript&&(q=document.currentScript.src),_scriptDir&&
(q=_scriptDir),0!==q.indexOf("blob:")?q=q.substr(0,q.lastIndexOf("/")+1):q="",r=function(a){var c=new XMLHttpRequest;c.open("GET",a,!1);c.send(null);return c.responseText},m&&(t=function(a){var c=new XMLHttpRequest;c.open("GET",a,!1);c.responseType="arraybuffer";c.send(null);return new Uint8Array(c.response)});var aa=b.print||console.log.bind(console),x=b.printErr||console.warn.bind(console);for(h in e)e.hasOwnProperty(h)&&(b[h]=e[h]);e=null;var y;b.wasmBinary&&(y=b.wasmBinary);var noExitRuntime;
b.noExitRuntime&&(noExitRuntime=b.noExitRuntime);"object"!==typeof WebAssembly&&x("no native wasm support detected");var z,ba=new WebAssembly.Table({initial:22,maximum:22,element:"anyfunc"}),A=!1;"undefined"!==typeof TextDecoder&&new TextDecoder("utf8");"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");var B,C,D;
function E(a){B=a;b.HEAP8=new Int8Array(a);b.HEAP16=new Int16Array(a);b.HEAP32=D=new Int32Array(a);b.HEAPU8=C=new Uint8Array(a);b.HEAPU16=new Uint16Array(a);b.HEAPU32=new Uint32Array(a);b.HEAPF32=new Float32Array(a);b.HEAPF64=new Float64Array(a)}var F=b.INITIAL_MEMORY||16777216;b.wasmMemory?z=b.wasmMemory:z=new WebAssembly.Memory({initial:F/65536,maximum:32768});z&&(B=z.buffer);F=B.byteLength;E(B);D[528]=5245152;
function G(a){for(;0<a.length;){var c=a.shift();if("function"==typeof c)c(b);else{var d=c.H;"number"===typeof d?void 0===c.F?b.dynCall_v(d):b.dynCall_vi(d,c.F):d(void 0===c.F?null:c.F)}}}var H=[],I=[],ca=[],J=[];function da(){var a=b.preRun.shift();H.unshift(a)}var K=0,L=null,M=null;b.preloadedImages={};b.preloadedAudios={};function w(a){if(b.onAbort)b.onAbort(a);aa(a);x(a);A=!0;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}
function N(){var a=O;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var O="voronoi_wasm.wasm";if(!N()){var P=O;O=b.locateFile?b.locateFile(P,q):q+P}function Q(){try{if(y)return new Uint8Array(y);if(t)return t(O);throw"both async and sync fetching of the wasm failed";}catch(a){w(a)}}
function ea(){return y||!k&&!m||"function"!==typeof fetch?new Promise(function(a){a(Q())}):fetch(O,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+O+"'";return a.arrayBuffer()}).catch(function(){return Q()})}I.push({H:function(){R()}});function S(){return 0<S.G}
var ha={d:function(a){return fa(a)},c:function(a){"uncaught_exception"in S?S.G++:S.G=1;throw a;},a:function(a,c,d){C.copyWithin(a,c,c+d)},b:function(a){var c=C.length;if(2147483648<a)return!1;for(var d=1;4>=d;d*=2){var f=c*(1+.2/d);f=Math.min(f,a+100663296);f=Math.max(16777216,a,f);0<f%65536&&(f+=65536-f%65536);a:{try{z.grow(Math.min(2147483648,f)-B.byteLength+65535>>>16);E(z.buffer);var g=1;break a}catch(l){}g=void 0}if(g)return!0}return!1},memory:z,table:ba},ia=function(){function a(g){b.asm=g.exports;
K--;b.monitorRunDependencies&&b.monitorRunDependencies(K);0==K&&(null!==L&&(clearInterval(L),L=null),M&&(g=M,M=null,g()))}function c(g){a(g.instance)}function d(g){return ea().then(function(l){return WebAssembly.instantiate(l,f)}).then(g,function(l){x("failed to asynchronously prepare wasm: "+l);w(l)})}var f={a:ha};K++;b.monitorRunDependencies&&b.monitorRunDependencies(K);if(b.instantiateWasm)try{return b.instantiateWasm(f,a)}catch(g){return x("Module.instantiateWasm callback failed with error: "+
g),!1}(function(){if(y||"function"!==typeof WebAssembly.instantiateStreaming||N()||"function"!==typeof fetch)return d(c);fetch(O,{credentials:"same-origin"}).then(function(g){return WebAssembly.instantiateStreaming(g,f).then(c,function(l){x("wasm streaming compile failed: "+l);x("falling back to ArrayBuffer instantiation");d(c)})})})();return{}}();b.asm=ia;var R=b.___wasm_call_ctors=function(){return(R=b.___wasm_call_ctors=b.asm.e).apply(null,arguments)};
b._free=function(){return(b._free=b.asm.f).apply(null,arguments)};
var fa=b._malloc=function(){return(fa=b._malloc=b.asm.g).apply(null,arguments)},ja=b._emscripten_bind_Voronoi_Voronoi_0=function(){return(ja=b._emscripten_bind_Voronoi_Voronoi_0=b.asm.h).apply(null,arguments)},ka=b._emscripten_bind_Voronoi_setLimits_5=function(){return(ka=b._emscripten_bind_Voronoi_setLimits_5=b.asm.i).apply(null,arguments)},la=b._emscripten_bind_Voronoi_addSite_2=function(){return(la=b._emscripten_bind_Voronoi_addSite_2=b.asm.j).apply(null,arguments)},ma=b._emscripten_bind_Voronoi_compute_0=
function(){return(ma=b._emscripten_bind_Voronoi_compute_0=b.asm.k).apply(null,arguments)},na=b._emscripten_bind_Voronoi_computeEdges_0=function(){return(na=b._emscripten_bind_Voronoi_computeEdges_0=b.asm.l).apply(null,arguments)},oa=b._emscripten_bind_Voronoi_computeCells_0=function(){return(oa=b._emscripten_bind_Voronoi_computeCells_0=b.asm.m).apply(null,arguments)},pa=b._emscripten_bind_Voronoi_getCellNumVertices_1=function(){return(pa=b._emscripten_bind_Voronoi_getCellNumVertices_1=b.asm.n).apply(null,
arguments)},qa=b._emscripten_bind_Voronoi_getCellVertexX_2=function(){return(qa=b._emscripten_bind_Voronoi_getCellVertexX_2=b.asm.o).apply(null,arguments)},ra=b._emscripten_bind_Voronoi_getCellVertexY_2=function(){return(ra=b._emscripten_bind_Voronoi_getCellVertexY_2=b.asm.p).apply(null,arguments)},sa=b._emscripten_bind_Voronoi_getNumEdges_0=function(){return(sa=b._emscripten_bind_Voronoi_getNumEdges_0=b.asm.q).apply(null,arguments)},ta=b._emscripten_bind_Voronoi_getEdgeX1_1=function(){return(ta=
b._emscripten_bind_Voronoi_getEdgeX1_1=b.asm.r).apply(null,arguments)},ua=b._emscripten_bind_Voronoi_getEdgeY1_1=function(){return(ua=b._emscripten_bind_Voronoi_getEdgeY1_1=b.asm.s).apply(null,arguments)},va=b._emscripten_bind_Voronoi_getEdgeX2_1=function(){return(va=b._emscripten_bind_Voronoi_getEdgeX2_1=b.asm.t).apply(null,arguments)},wa=b._emscripten_bind_Voronoi_getEdgeY2_1=function(){return(wa=b._emscripten_bind_Voronoi_getEdgeY2_1=b.asm.u).apply(null,arguments)},xa=b._emscripten_bind_Voronoi_getSiteX_1=
function(){return(xa=b._emscripten_bind_Voronoi_getSiteX_1=b.asm.v).apply(null,arguments)},ya=b._emscripten_bind_Voronoi_getSiteY_1=function(){return(ya=b._emscripten_bind_Voronoi_getSiteY_1=b.asm.w).apply(null,arguments)},za=b._emscripten_bind_Voronoi_clear_0=function(){return(za=b._emscripten_bind_Voronoi_clear_0=b.asm.x).apply(null,arguments)},Aa=b._emscripten_bind_Voronoi___destroy___0=function(){return(Aa=b._emscripten_bind_Voronoi___destroy___0=b.asm.y).apply(null,arguments)},Ba=b._emscripten_bind_VoidPtr___destroy___0=
function(){return(Ba=b._emscripten_bind_VoidPtr___destroy___0=b.asm.z).apply(null,arguments)};b.dynCall_vi=function(){return(b.dynCall_vi=b.asm.A).apply(null,arguments)};b.asm=ia;var T;b.then=function(a){if(T)a(b);else{var c=b.onRuntimeInitialized;b.onRuntimeInitialized=function(){c&&c();a(b)}}return b};M=function Ca(){T||U();T||(M=Ca)};
function U(){function a(){if(!T&&(T=!0,b.calledRun=!0,!A)){G(I);G(ca);if(b.onRuntimeInitialized)b.onRuntimeInitialized();if(b.postRun)for("function"==typeof b.postRun&&(b.postRun=[b.postRun]);b.postRun.length;){var c=b.postRun.shift();J.unshift(c)}G(J)}}if(!(0<K)){if(b.preRun)for("function"==typeof b.preRun&&(b.preRun=[b.preRun]);b.preRun.length;)da();G(H);0<K||(b.setStatus?(b.setStatus("Running..."),setTimeout(function(){setTimeout(function(){b.setStatus("")},1);a()},1)):a())}}b.run=U;
if(b.preInit)for("function"==typeof b.preInit&&(b.preInit=[b.preInit]);0<b.preInit.length;)b.preInit.pop()();noExitRuntime=!0;U();function V(){}V.prototype=Object.create(V.prototype);V.prototype.constructor=V;V.prototype.C=V;V.D={};b.WrapperObject=V;function W(a){return(a||V).D}b.getCache=W;function X(a,c){var d=W(c),f=d[a];if(f)return f;f=Object.create((c||V).prototype);f.B=a;return d[a]=f}b.wrapPointer=X;b.castObject=function(a,c){return X(a.B,c)};b.NULL=X(0);
b.destroy=function(a){if(!a.__destroy__)throw"Error: Cannot destroy object. (Did you create it yourself?)";a.__destroy__();delete W(a.C)[a.B]};b.compare=function(a,c){return a.B===c.B};b.getPointer=function(a){return a.B};b.getClass=function(a){return a.C};function Y(){this.B=ja();W(Y)[this.B]=this}Y.prototype=Object.create(V.prototype);Y.prototype.constructor=Y;Y.prototype.C=Y;Y.D={};b.Voronoi=Y;
Y.prototype.setLimits=function(a,c,d,f,g){var l=this.B;a&&"object"===typeof a&&(a=a.B);c&&"object"===typeof c&&(c=c.B);d&&"object"===typeof d&&(d=d.B);f&&"object"===typeof f&&(f=f.B);g&&"object"===typeof g&&(g=g.B);ka(l,a,c,d,f,g)};Y.prototype.addSite=function(a,c){var d=this.B;a&&"object"===typeof a&&(a=a.B);c&&"object"===typeof c&&(c=c.B);la(d,a,c)};Y.prototype.compute=function(){ma(this.B)};Y.prototype.computeEdges=function(){na(this.B)};Y.prototype.computeCells=function(){oa(this.B)};
Y.prototype.getCellNumVertices=function(a){var c=this.B;a&&"object"===typeof a&&(a=a.B);return pa(c,a)};Y.prototype.getCellVertexX=function(a,c){var d=this.B;a&&"object"===typeof a&&(a=a.B);c&&"object"===typeof c&&(c=c.B);return qa(d,a,c)};Y.prototype.getCellVertexY=function(a,c){var d=this.B;a&&"object"===typeof a&&(a=a.B);c&&"object"===typeof c&&(c=c.B);return ra(d,a,c)};Y.prototype.getNumEdges=function(){return sa(this.B)};
Y.prototype.getEdgeX1=function(a){var c=this.B;a&&"object"===typeof a&&(a=a.B);return ta(c,a)};Y.prototype.getEdgeY1=function(a){var c=this.B;a&&"object"===typeof a&&(a=a.B);return ua(c,a)};Y.prototype.getEdgeX2=function(a){var c=this.B;a&&"object"===typeof a&&(a=a.B);return va(c,a)};Y.prototype.getEdgeY2=function(a){var c=this.B;a&&"object"===typeof a&&(a=a.B);return wa(c,a)};Y.prototype.getSiteX=function(a){var c=this.B;a&&"object"===typeof a&&(a=a.B);return xa(c,a)};
Y.prototype.getSiteY=function(a){var c=this.B;a&&"object"===typeof a&&(a=a.B);return ya(c,a)};Y.prototype.clear=function(){za(this.B)};Y.prototype.__destroy__=function(){Aa(this.B)};function Z(){throw"cannot construct a VoidPtr, no constructor in IDL";}Z.prototype=Object.create(V.prototype);Z.prototype.constructor=Z;Z.prototype.C=Z;Z.D={};b.VoidPtr=Z;Z.prototype.__destroy__=function(){Ba(this.B)};


  return VORONOI_WASM
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
      module.exports = VORONOI_WASM;
    else if (typeof define === 'function' && define['amd'])
      define([], function() { return VORONOI_WASM; });
    else if (typeof exports === 'object')
      exports["VORONOI_WASM"] = VORONOI_WASM;
    
// var Voronoi = VORONOI_WASM.Voronoi;
// if (typeof module != 'undefined'){
//   module.exports = Voronoi;
// }